name: github-actions-example-pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/angular-github-actions
      - run: |
          cd frontend
          npm ci
          npm run test

